name: Release
on:
  push:
    branches:    
      - main
    tags:        
      - v*
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: report.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: report.pdf
          body: "Beispieldokument"
